import os
import sys
from github import Github, Auth
from google import genai

def main():
    # 1. Setup Environment Variables
    # These are automatically populated by your GitHub Action YAML
    token = os.getenv("GITHUB_TOKEN")
    gemini_key = os.getenv("GEMINI_API_KEY")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    pr_num = os.getenv("PR_NUMBER")
    commit_sha = os.getenv("COMMIT_SHA")
    
    # Critical Check: We need the API keys and Repo name to proceed
    if not all([token, gemini_key, repo_name]):
        print("❌ Error: Missing Critical API Credentials (GITHUB_TOKEN or GEMINI_API_KEY).")
        sys.exit(1)

    try:
        # 2. Initialize Clients
        # Forced to Stable v1 (Removing v1beta to avoid 404 errors)
        client = genai.Client(api_key=gemini_key)
        gh = Github(auth=Auth.Token(token))
        repo = gh.get_repo(repo_name)

        diff_content = ""
        target_object = None

        # 3. Context-Aware Extraction (PR vs. Merge/Push)
        # If PR_NUMBER exists, we are in a Pull Request flow
        if pr_num and pr_num.isdigit():
            print(f"🔍 Context: Pull Request #{pr_num} Detected.")
            target_object = repo.get_pull(int(pr_num))
            for file in target_object.get_files():
                if file.patch:
                    diff_content += f"\n--- File: {file.filename} ---\n{file.patch}\n"
        
        # If no PR_NUMBER, we look at the specific Commit (Merge to Main)
        elif commit_sha:
            print(f"🔍 Context: Merge/Push Detected (SHA: {commit_sha[:7]}).")
            commit = repo.get_commit(commit_sha)
            target_object = commit
            for file in commit.files:
                if file.patch:
                    diff_content += f"\n--- File: {file.filename} ---\n{file.patch}\n"
        
        else:
            print("❌ Error: No PR Number or Commit SHA provided.")
            sys.exit(1)

        # 4. Content Validation
        if not diff_content:
            print("⚠️ No code changes found to document. Skipping AI call.")
            return

        # 5. Gemini Analysis (Stable 1.5-Flash)
        print("🤖 Consulting Gemini 1.5-Flash (Stable Tier)...")
        
        prompt = f"""
        Act as a Senior Technical Writer following the Diátaxis framework. 
        Analyze the code changes below and generate a concise 'How-to' guide.
        
        Format your response in Markdown:
        ### 🎯 Feature Overview
        (2 sentences on the change)
        
        ### 🛠️ Usage / Implementation
        (Step-by-step or code snippet for the developer)
        
        ### 📝 Prerequisites
        (Dependencies or config required)
        
        CODE DIFFS:
        {diff_content[:10000]}
        """

        # Using the clean model ID on the stable endpoint
        response = client.models.generate_content(
            model="gemini-1.5-flash", 
            contents=prompt
        )
        
        if not response.text:
            print("⚠️ AI returned an empty response.")
            return

        # 6. Smart Posting (Handles PR comments or Commit comments)
        comment_header = "## 📘 Automated AI Documentation Draft\n\n"
        comment_footer = "\n\n---\n*Generated by Broadcom TechDocs AI Pipeline (Stable 1.5-Flash)*"
        full_comment = f"{comment_header}{response.text}{comment_footer}"

        if hasattr(target_object, 'create_issue_comment'):
            # This is a Pull Request
            target_object.create_issue_comment(full_comment)
            print("🚀 Success! Posted to Pull Request conversation.")
        else:
            # This is a direct Commit (after Merge)
            target_object.create_comment(full_comment)
            print("🚀 Success! Posted to Commit history.")

    except Exception as e:
        print(f"❌ Critical Error: {str(e)}")
        # We exit with 1 to ensure the GitHub Action shows a Red X if it fails
        sys.exit(1)

if __name__ == "__main__":
    main()
