import os
import sys
from github import Github, Auth
from google import genai

def main():
    # 1. Setup environment variables (Provided by GitHub Actions)
    token = os.getenv("GITHUB_TOKEN")
    gemini_key = os.getenv("GEMINI_API_KEY")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    pr_num = os.getenv("PR_NUMBER")
    
    if not all([token, gemini_key, repo_name, pr_num]):
        print("❌ Error: Missing required environment variables.")
        sys.exit(1)

    print(f"🔍 Starting Logic Extraction for PR #{pr_num} in {repo_name}...")

    try:
        # 2. Initialize Clients
        # Using v1beta to access the latest Gemini 3 series models
        client = genai.Client(api_key=gemini_key, http_options={'api_version': 'v1beta'})
        gh = Github(auth=Auth.Token(token))
        
        repo = gh.get_repo(repo_name)
        pr = repo.get_pull(int(pr_num))

        # 3. Extract Code Diffs
        diff_content = ""
        for file in pr.get_files():
            # Include Java, Python, and configuration files
            if file.filename.endswith(('.py', '.java', '.xml', '.gradle', '.js', '.ts')):
                if file.patch:
                    diff_content += f"\n--- File: {file.filename} ---\n{file.patch}\n"

        if not diff_content:
            print("⚠️ No relevant code changes found to document.")
            return

        # 4. Generate Documentation with Gemini 3 Flash
        model_id = "gemini-3-flash-preview"
        prompt = f"""
        Act as a Senior Technical Writer. Analyze the following code changes and generate a 
        concise 'How-to' guide for a developer audience.
        
        Format:
        ### 🎯 Feature Overview
        (Describe what this change does in 2 sentences)
        
        ### 🛠️ Usage / Implementation
        (Step-by-step instructions or code snippets showing how to use the new logic)
        
        ### 📝 Prerequisites
        (List any new dependencies or requirements)
        
        CODE DIFFS:
        {diff_content}
        """

        print(f"🤖 Consulting {model_id}...")
        response = client.models.generate_content(model=model_id, contents=prompt)
        
        # 5. Post to GitHub
        comment_body = f"## 📘 Automated AI Documentation Draft\n\n{response.text}\n\n---\n*Generated by Gemini 3 Flash via GitHub Actions*"
        pr.create_issue_comment(comment_body)
        
        print("🚀 Success! Documentation comment posted to the PR.")

    except Exception as e:
        print(f"❌ Critical Error: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()
