import os
import sys
from github import Github, Auth
from google import genai

def main():
    # 1. Setup environment variables (Provided by GitHub Actions)
    token = os.getenv("GITHUB_TOKEN")
    gemini_key = os.getenv("GEMINI_API_KEY")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    pr_num = os.getenv("PR_NUMBER")
    
    if not all([token, gemini_key, repo_name, pr_num]):
        print("❌ Error: Missing required environment variables.")
        sys.exit(1)

    print(f"🔍 Starting Logic Extraction for PR #{pr_num} in {repo_name}...")

    try:
        # 2. Initialize Clients
        # Using the standard client to avoid 404/Preview errors
        client = genai.Client(api_key=gemini_key)
        gh = Github(auth=Auth.Token(token))
        
        repo = gh.get_repo(repo_name)
        pr = repo.get_pull(int(pr_num))

        # 3. Extract Code Diffs (with Quota Protection)
        diff_content = ""
        MAX_CHAR_LIMIT = 8000
        
        for file in pr.get_files():
            # Target technical writing relevant files
            if file.filename.endswith(('.py', '.java', '.xml', '.gradle', '.js', '.ts', '.sh')):
                if file.patch:
                    diff_content += f"\n--- File: {file.filename} ---\n{file.patch}\n"
        
        # Ensure we don't send too many tokens on a free account
        diff_content = diff_content[:MAX_CHAR_LIMIT]

        if not diff_content:
            print("⚠️ No relevant code changes found to document.")
            return

        # 4. Generate Documentation (Stable Model Path)
        # Using gemini-1.5-flash for maximum uptime on personal accounts
        model_id = "gemini-1.5-flash"
        
        prompt = f"""
        Act as a Senior Technical Writer following the Diátaxis framework. 
        Analyze the code changes below and generate a concise 'How-to' guide.
        
        Format:
        ### 🎯 Feature Overview
        (2 sentences on the change)
        
        ### 🛠️ Usage / Implementation
        (Step-by-step or code snippet for the developer)
        
        ### 📝 Prerequisites
        (Dependencies or config required)
        
        CODE DIFFS:
        {diff_content}
        """

        print(f"🤖 Consulting {model_id} via Stable Pipeline...")
        
        # Calling the model using the direct ID which is available to all users
        response = client.models.generate_content(
            model=model_id, 
            contents=prompt
        )
        
        # 5. Post to GitHub
        if not response.text:
            print("❌ AI returned an empty response.")
            return

        comment_body = (
            f"## 📘 Automated AI Documentation Draft\n\n"
            f"{response.text}\n\n"
            f"---\n*Generated by Broadcom TechDocs AI (Gemini 1.5 Flash)*"
        )
        
        pr.create_issue_comment(comment_body)
        print("🚀 Success! Documentation comment posted to the PR.")

    except Exception as e:
        # Graceful error handling for the Demo
        if "429" in str(e):
            print("❌ Quota hit: Wait 60 seconds and re-run.")
        elif "404" in str(e):
            print(f"❌ Model Error: {model_id} path not found. Check AI Studio availability.")
        else:
            print(f"❌ Critical Error: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()
